---
  kind: Service
  apiVersion: v1
  metadata:
    name: openvpn-svc
  spec:
    selector:
      app: openvpn
    ports:
    - name: http
      protocol: TCP
      port: 943
      targetPort: 943
    - name: vpn
      protocol: UDP
      port: 1194
      targetPort: 1194
    - name: vpntcp
      protocol: TCP
      port: 9443
      targetPort: 9443
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openvpn
  namespace: openvpn
  labels:
    app: openvpn
    track: stable
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: openvpn
        app: openvpn
    spec:
      containers:
      - image: linuxserver/openvpn-as
        name: openvpn
        ports:
        - containerPort: 943
          name: http
          protocol: TCP
        - containerPort: 1194
          name: vpn
          protocol: UDP
        - containerPort: 9443
          name: vpntcp
          port: 9443
          protocol: TCP
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
